In [0]:
import numpy as np

# creating array (1 dimentional and 2 dimensional array)

In [0]:
my_list = [1,2,3]

In [5]:
my_list

[1, 2, 3]

In [0]:
arr = np.array(my_list) #one dimensional array

In [7]:
arr

array([1, 2, 3])

In [0]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
my_arr = np.array(my_mat) #two dimensional array
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#using built in functions to create numpy array
np.arange(0,10, 2)#generates array from low end to highend

array([0, 2, 4, 6, 8])

# Random number generation

In [0]:

# rand generates random number betwwen 0 and 1. here random number between 0 and 1 with 
# 5 rows,4 collumns is generated.
np.random.rand(5,4) 

array([[ 0.6485795 ,  0.79535874,  0.56073951,  0.73682383],
       [ 0.33779618,  0.08024333,  0.13778647,  0.42883558],
       [ 0.92620162,  0.33063106,  0.53421953,  0.37859707],
       [ 0.05084002,  0.4550901 ,  0.12290787,  0.67366539],
       [ 0.09129496,  0.92703337,  0.87121784,  0.04702162]])

In [0]:
#randn generates any random number of give array size. here random number of 2*2 matrix is generated.
np.random.randn(2,2) 

array([[-1.10512081, -0.1490814 ],
       [ 1.31783267,  2.35742408]])

In [0]:
#randint generateas random number from 1 to 100
np.random.randint(1,100)

5

In [0]:
#generates  5 random numbers from 1 to 100
np.random.randint(1,100,5)

array([20, 82, 73, 45, 43])

# seed() gives same random number 

eg. seed(x) always gives output y. seed(a) always gives output b. 

In [0]:
np.random.seed(10)
np.random.random()


0.771320643266746

In [0]:
np.random.seed(10)
np.random.random()

0.771320643266746

# Shape and reshape

In [0]:
arr = np.arange(25)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.shape

(25,)

In [0]:
#reshaping the array
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
a=np.array(([2,5],[5,6],[6,7]))

In [0]:
a

array([[2, 5],
       [5, 6],
       [6, 7]])

In [0]:
#finding shape of array 
a.shape

(3, 2)

In [0]:
a.reshape(2,3)

array([[2, 5, 5],
       [6, 6, 7]])

In [0]:
arr.shape

(25,)

In [0]:
#datatype in array
arr.dtype

dtype('int32')

# Slicing


In [0]:
arr = np.arange(0,10)

In [0]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#INDEXING
arr[1]

1

In [0]:
arr[1:5] #slice notation

array([1, 2, 3, 4])

In [0]:
arr[:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5:]

array([5, 6, 7, 8, 9])

In [0]:
arr[0:5] =100

In [0]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [0]:
 arr
    

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [0]:
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [0]:
slice_arr[:] = 99

In [0]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [0]:
arr #values are not copied rather the memory address is sent , point to be noted carefully

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
#if we want copy of value only we can use copy function
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy[6:] =100
arr_copy

array([ 99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100])

In [0]:
#not changed in the initial arrar i.e arr as values are only copied to the array arr_copy
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
#2D array , also known as matrix

arr_mat = np.array([[5,10,15], [20,25,30], [30,35,40]])
arr_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

# Indexing  in Numpy array

In [0]:
#indexing
arr_mat[0,0]

5

In [0]:
arr_mat[0][0]

5

In [0]:
arr_mat[0]

array([ 5, 10, 15])

In [0]:
arr_mat[2,2]

40

In [0]:
arr_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [0]:
arr_mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr_mat[2:, 2:]

array([[40]])

In [0]:
arr_mat[:3, 1:2]

array([[10],
       [25],
       [35]])

In [0]:
arr_mat[:, 2:3]

array([[15],
       [30],
       [40]])

In [0]:
# matrix and Vector Operations

#Vector dotproduct and cos angle
a = np.array([1,2,3])
b = np.array([1,5,7])
amag = np.linalg.norm(a)
bmag = np.linalg.norm(b)
cos_angle = a.dot(b) / ( amag * bmag)
cos_angle



0.98754143975738806

In [0]:
a.dot(b)

32

In [0]:
cosangle = np.arccos(cos_angle)
cosangle

0.15801592211305823

In [0]:
#Vector Sine Angle and Cross Product


In [0]:
c = np.cross(a, b)
c

array([-1, -4,  3])

In [0]:
c_mag = np.linalg.norm(c)
c_mag

5.0990195135927845

In [0]:
amag = np.linalg.norm(a)
bmag = np.linalg.norm(b)

In [0]:
sin_angle = c_mag / ( amag * bmag)
sin_angle

0.1573591584938886

In [0]:
sinangle = np.arcsin(sin_angle)
sinangle

0.15801592211305715

In [0]:
#matrix 
#matrix Inverse
A = np.array([[1,2], [3,4]])
A


array([[1, 2],
       [3, 4]])

In [0]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
#matrix determinant
A_det = np.linalg.det(A)
A_det


-2.0000000000000004

In [0]:
np.diag(A) #printing diagonal elements]

array([1, 4])

In [0]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [0]:
# We need install numpy in order to import it
import numpy as np
 
# input two matrices
mat1 = ([1,2,4],[3,4,5])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
 
# This will return dot product
res = np.dot(mat1,mat2)
 
# print resulted matrix
print(res)

[[ 37 240  48]
 [ 59 316  81]]


In [0]:
mat3 =([1,2,3],[4,5,6])
mat4 =([4,5,6],[1,2,3])
res1 = np.cross(mat3,mat4)

In [0]:
res1

array([[-3,  6, -3],
       [ 3, -6,  3]])